# Generated by Django 5.2.18 on 2026-10-07 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0004_pagamentoplataforma_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitada_por_id', models.UUIDField()),
                ('tipo', models.CharField(choices=[('consultorio', 'Dados do consultório'), ('prontuarios', 'Prontuários do profissional')], max_length=12)),
                ('arquivos', models.PositiveIntegerField(default=0)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
