# Generated by Django 5.2.18 on 2026-10-07 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0003_rls'),
        ('contas', '0002_rls_vinculo'),
        ('pacientes', '0002_rls'),
        ('plataforma', '0003_consultorio_cobra_falta_tardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operadora', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
            ],
            options={
                'ordering': ['operadora'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('particular', 'Particular'), ('convenio', 'Convênio'), ('aluguel', 'Aluguel de sala')], max_length=12)),
                ('origem', models.CharField(choices=[('consulta', 'Consulta realizada'), ('falta_tardia', 'Cancelamento tardio'), ('recorrente', 'Cobrança recorrente'), ('manual', 'Lançamento manual')], default='consulta', max_length=14)),
                ('primeira_consulta', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, max_length=160)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('transferencia', 'Transferência'), ('outro', 'Outro')], max_length=14)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='agenda.consulta')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.convenio')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='pacientes.paciente')),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pacientes.pagador')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='contas.profissional')),
            ],
            options={
                'ordering': ['-vencimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtendimentoConvenio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('realizado', 'Realizado'), ('faturado', 'Faturado'), ('pago', 'Pago'), ('glosado', 'Glosado')], default='realizado', max_length=10)),
                ('carteirinha', models.CharField(blank=True, max_length=40)),
                ('demonstrativo', models.CharField(blank=True, help_text='Lote ou demonstrativo da operadora.', max_length=60)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_glosado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo_glosa', models.CharField(blank=True, max_length=200)),
                ('faturado_em', models.DateTimeField(blank=True, null=True)),
                ('retorno_em', models.DateTimeField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_convenio', to='financeiro.lancamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('nome_pagador', models.CharField(max_length=160)),
                ('cpf_pagador', models.CharField(max_length=11)),
                ('caminho', models.CharField(max_length=300)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('numero_nota_externa', models.CharField(blank=True, max_length=40)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recibo', to='financeiro.lancamento')),
            ],
        ),
        migrations.CreateModel(
            name='RegraRepasse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.CharField(blank=True, choices=[('', 'Qualquer atendimento'), ('particular', 'Particular'), ('convenio', 'Convênio'), ('primeira_consulta', 'Primeira consulta')], default='', max_length=20, verbose_name='vale para')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='percentual do profissional (%)')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor fixo por atendimento')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contas.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.DateField(help_text='Primeiro dia do mês em que o dinheiro entrou.')),
                ('base', models.DecimalField(decimal_places=2, help_text='Valor efetivamente recebido.', max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('a_pagar', 'A pagar'), ('pago', 'Pago')], default='a_pagar', max_length=10)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('pago_por_id', models.UUIDField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('lancamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repasse', to='financeiro.lancamento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repasses', to='contas.profissional')),
            ],
            options={
                'ordering': ['-competencia', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TabelaValor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('primeira_consulta', 'Primeira consulta')], default='consulta', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='financeiro.convenio')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contas.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='CobrancaRecorrente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(default='Aluguel de sala', max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=10, help_text='Dia do mês (1 a 28).')),
                ('ativa', models.BooleanField(default=True)),
                ('ultima_competencia', models.DateField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contas.profissional')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('dia_vencimento__gte', 1), ('dia_vencimento__lte', 28)), name='dia_vencimento_valido')],
            },
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.UniqueConstraint(fields=('consultorio', 'operadora'), name='convenio_unico'),
        ),
        migrations.AddConstraint(
            model_name='lancamento',
            constraint=models.UniqueConstraint(condition=models.Q(('consulta__isnull', False)), fields=('consulta', 'origem'), name='um_lancamento_por_consulta_e_origem'),
        ),
        migrations.AddConstraint(
            model_name='lancamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='lancamento_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='recibo',
            constraint=models.UniqueConstraint(fields=('consultorio', 'numero'), name='recibo_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='regrarepasse',
            constraint=models.UniqueConstraint(fields=('profissional', 'aplicacao'), name='regra_repasse_unica'),
        ),
        migrations.AddConstraint(
            model_name='regrarepasse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('percentual__isnull', False), ('valor_fixo__isnull', True)), models.Q(('percentual__isnull', True), ('valor_fixo__isnull', False)), _connector='OR'), name='regra_percentual_ou_fixo'),
        ),
        migrations.AddConstraint(
            model_name='regrarepasse',
            constraint=models.CheckConstraint(condition=models.Q(('percentual__isnull', True), models.Q(('percentual__gte', 0), ('percentual__lte', 100)), _connector='OR'), name='regra_percentual_valido'),
        ),
        migrations.AddConstraint(
            model_name='tabelavalor',
            constraint=models.UniqueConstraint(condition=models.Q(('convenio__isnull', False)), fields=('profissional', 'convenio', 'tipo'), name='valor_convenio_unico'),
        ),
        migrations.AddConstraint(
            model_name='tabelavalor',
            constraint=models.UniqueConstraint(condition=models.Q(('convenio__isnull', True)), fields=('profissional', 'tipo'), name='valor_particular_unico'),
        ),
        migrations.AddConstraint(
            model_name='tabelavalor',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='valor_nao_negativo'),
        ),
    ]
