# Generated by Django 5.2.18 on 2026-10-07 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0002_rls_vinculo'),
        ('plataforma', '0002_contrato_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('casal', 'Casal'), ('familia', 'Família'), ('grupo', 'Grupo')], max_length=10)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, help_text='Somente números. Pode ficar vazio (ex.: criança).', max_length=11)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('convenio', models.CharField(blank=True, max_length=80, verbose_name='convênio')),
                ('carteirinha', models.CharField(blank=True, max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('exige_aprovacao', models.BooleanField(default=False, help_text='A primeira consulta sempre passa por aprovação.', verbose_name='retornos também exigem aprovação')),
                ('ultimo_atendimento_em', models.DateTimeField(blank=True, null=True)),
                ('mesclado_em', models.DateTimeField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='plataforma.consultorio')),
                ('mesclado_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesclados', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pagador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(max_length=11)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagador', to='pacientes.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipanteGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='pacientes.grupoatendimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='contas.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('recebe_avisos', models.BooleanField(default=True)),
                ('pode_pagar', models.BooleanField(default=False, verbose_name='é o pagador')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='pacientes.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('cpf', ''), _negated=True), ('mesclado_em__isnull', True)), fields=('consultorio', 'cpf'), name='cpf_unico_por_consultorio'),
        ),
        migrations.AddConstraint(
            model_name='participantegrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'paciente'), name='participante_unico'),
        ),
        migrations.AddConstraint(
            model_name='profissionalpaciente',
            constraint=models.UniqueConstraint(fields=('paciente', 'profissional'), name='profissional_paciente_unico'),
        ),
    ]
