# Generated by Django 5.2.18 on 2026-10-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_contrato_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='cobra_falta_tardia',
            field=models.BooleanField(default=False, verbose_name='cobrar cancelamento tardio'),
        ),
    ]
