# Generated by Django 5.2.18 on 2026-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_consultorio_cobra_falta_tardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoplataforma',
            name='vencimento',
            field=models.DateField(blank=True, help_text='Depois dele, sem pagamento, começa a carência.', null=True),
        ),
    ]
