# Generated by Django 5.2.18 on 2026-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_rls_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_passo_totp',
            field=models.BigIntegerField(blank=True, help_text='Ultimo passo de 30 s aceito (anti-reuso do codigo).', null=True),
        ),
    ]
