# Generated by Django 5.2.18 on 2026-10-07 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_rls'),
        ('plataforma', '0003_consultorio_cobra_falta_tardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoLGPD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('exclusao', 'Exclusão dos meus dados'), ('copia', 'Cópia dos meus dados'), ('correcao', 'Correção de dados')], max_length=10)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('atendida', 'Atendida')], default='aberta', max_length=10)),
                ('atendida_por_id', models.UUIDField(blank=True, null=True)),
                ('atendida_em', models.DateTimeField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_lgpd', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CodigoAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('expira_em', models.DateTimeField()),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'criado_em'], name='codigo_email_criado_idx')],
            },
        ),
    ]
