# Generated by Django 5.2.18 on 2026-10-07 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_rls'),
        ('plataforma', '0003_consultorio_cobra_falta_tardia'),
        ('portal', '0002_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaPush',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('endpoint', models.TextField()),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_push', to='pacientes.paciente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('paciente', 'endpoint'), name='assinatura_push_unica')],
            },
        ),
    ]
