# Generated by Django 5.2.18 on 2026-10-07 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0004_alter_aviso_canal'),
        ('contas', '0002_rls_vinculo'),
        ('plataforma', '0003_consultorio_cobra_falta_tardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCalendario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('provedor', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Outlook / Microsoft 365')], max_length=12)),
                ('email_conta', models.CharField(blank=True, max_length=254)),
                ('token_acesso_cifrado', models.TextField(blank=True)),
                ('token_refresh_cifrado', models.TextField(blank=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('mostra_nome_paciente', models.BooleanField(default=False, help_text="Por padrão o evento externo mostra só 'Consulta' e o horário.", verbose_name='mostrar o nome do paciente no evento')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.CharField(blank=True, max_length=200)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_calendario', to='contas.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='EventoExterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(choices=[('psiq', 'Criado pelo PSIQ'), ('externo', 'Compromisso externo')], max_length=8)),
                ('id_externo', models.CharField(max_length=300)),
                ('titulo', models.CharField(blank=True, help_text='Titulo exportado (so eventos criados pelo PSIQ).', max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agenda.consulta')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='calendarios.contacalendario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contacalendario',
            constraint=models.UniqueConstraint(fields=('profissional', 'provedor'), name='conta_calendario_unica'),
        ),
        migrations.AddIndex(
            model_name='eventoexterno',
            index=models.Index(fields=['conta', 'origem', 'inicio'], name='evento_conta_origem_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoexterno',
            constraint=models.UniqueConstraint(fields=('conta', 'id_externo'), name='evento_externo_unico'),
        ),
    ]
