# Generated by Django 5.2.18 on 2026-10-07 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0004_pagamentoplataforma_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por_id', models.UUIDField()),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('linhas', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('previa', 'Prévia'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='previa', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('validas', models.PositiveIntegerField(default=0)),
                ('duplicadas', models.PositiveIntegerField(default=0)),
                ('com_erro', models.PositiveIntegerField(default=0)),
                ('importadas', models.PositiveIntegerField(default=0)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
