# Generated by Django 5.2.18 on 2026-10-07 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0003_rls'),
        ('contas', '0002_rls_vinculo'),
        ('pacientes', '0002_rls'),
        ('plataforma', '0002_contrato_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveDados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chave_cifrada', models.TextField()),
                ('ativa', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaves', to='contas.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentimentoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escopo', models.CharField(default='leitura', max_length=20)),
                ('termo_versao', models.CharField(blank=True, max_length=10)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('ip_aceite', models.GenericIPAddressField(blank=True, null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_revogacao', models.GenericIPAddressField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos', to='pacientes.paciente')),
                ('profissional_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contas.profissional')),
                ('profissional_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contas.profissional')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('comparecimento', 'Declaração de comparecimento'), ('declaracao', 'Declaração'), ('atestado', 'Atestado'), ('relatorio', 'Relatório')], max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('texto_base', models.TextField()),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('conjunto', 'Conjunto (casal ou família)')], default='individual', max_length=12)),
                ('ultimo_registro_em', models.DateTimeField(blank=True, null=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('excluido_por_id', models.UUIDField(blank=True, null=True)),
                ('exclusao_motivo', models.CharField(blank=True, max_length=300)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.contrato')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='pacientes.grupoatendimento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(help_text='Dono do prontuário.', on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='contas.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='LiberacaoLeitura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concedido_por_id', models.UUIDField()),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes', to='prontuario.prontuario')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('caminho', models.CharField(max_length=300)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('autor_id', models.UUIDField()),
                ('liberado_ao_paciente', models.BooleanField(default=False)),
                ('chave', models.ForeignKey(blank=True, help_text='Vazio: cifrado pela chave mestra (documento sem conteudo clinico).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='prontuario.chavedados')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='pacientes.paciente')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='prontuario.modelodocumento')),
                ('prontuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='prontuario.prontuario')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Delegacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('feita_por_id', models.UUIDField()),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contas.profissional')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contas.profissional')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes', to='prontuario.prontuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('caminho', models.CharField(max_length=300)),
                ('tamanho', models.PositiveIntegerField()),
                ('hash_sha256', models.CharField(max_length=64)),
                ('importado_historico', models.BooleanField(default=False)),
                ('enviado_por_id', models.UUIDField()),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='prontuario.chavedados')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='prontuario.prontuario')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('evolucao', 'Evolução'), ('anamnese', 'Anamnese'), ('prescricao_registro', 'Registro de prescrição'), ('outro', 'Outro')], default='evolucao', max_length=20)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agenda.consulta')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='prontuario.prontuario')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('conteudo_cifrado', models.TextField()),
                ('cid_cifrado', models.TextField(blank=True)),
                ('autor_id', models.UUIDField()),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='prontuario.chavedados')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='prontuario.registroclinico')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='chavedados',
            constraint=models.UniqueConstraint(condition=models.Q(('ativa', True)), fields=('profissional',), name='uma_chave_ativa_por_profissional'),
        ),
        migrations.AddConstraint(
            model_name='prontuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grupo__isnull', True), ('paciente__isnull', False)), models.Q(('grupo__isnull', False), ('paciente__isnull', True)), _connector='OR'), name='prontuario_paciente_ou_grupo'),
        ),
        migrations.AddConstraint(
            model_name='prontuario',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True), ('paciente__isnull', False)), fields=('paciente', 'profissional'), name='prontuario_unico_paciente_profissional'),
        ),
        migrations.AddConstraint(
            model_name='registroversao',
            constraint=models.UniqueConstraint(fields=('registro', 'numero'), name='versao_unica'),
        ),
    ]
