# Generated by Django 5.2.18 on 2026-10-07 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0002_rls_vinculo'),
        ('plataforma', '0002_contrato_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieRecorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('intervalo_semanas', models.PositiveSmallIntegerField(default=1)),
                ('repeticoes', models.PositiveSmallIntegerField()),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoHorario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('horario_desejado', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=12)),
                ('observacao', models.CharField(blank=True, help_text='Não registre informação clínica aqui.', max_length=300)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('decidida_por_id', models.UUIDField(blank=True, null=True)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['horario_desejado'],
            },
        ),
        migrations.CreateModel(
            name='AgendaRegra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=50)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_agenda', to='contas.profissional')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('email', 'E-mail')], max_length=10)),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação'), ('lembrete', 'Lembrete'), ('remarcacao', 'Remarcação'), ('cancelamento', 'Cancelamento')], max_length=14)),
                ('destinatario', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou')], default='pendente', max_length=10)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=200)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=12)),
                ('link_online', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Faltou')], default='agendada', max_length=12)),
                ('primeira_consulta', models.BooleanField(default=False)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_por', models.CharField(blank=True, choices=[('equipe', 'Consultório'), ('paciente', 'Paciente')], max_length=10)),
                ('falta_tardia', models.BooleanField(default=False, help_text='Cancelada pelo paciente dentro do prazo mínimo.')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='plataforma.consultorio')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
    ]
