# Generated by Django 5.2.18 on 2026-10-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('contas', '0002_rls_vinculo'),
        ('pacientes', '0001_initial'),
        ('plataforma', '0002_contrato_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.grupoatendimento'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='contas.profissional'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='agenda.consulta'),
        ),
        migrations.AddField(
            model_name='serierecorrencia',
            name='consultorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio'),
        ),
        migrations.AddField(
            model_name='serierecorrencia',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='contas.profissional'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='agenda.serierecorrencia'),
        ),
        migrations.AddField(
            model_name='solicitacaohorario',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao', to='agenda.consulta'),
        ),
        migrations.AddField(
            model_name='solicitacaohorario',
            name='consultorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plataforma.consultorio'),
        ),
        migrations.AddField(
            model_name='solicitacaohorario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='solicitacaohorario',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='contas.profissional'),
        ),
        migrations.AddConstraint(
            model_name='agendaregra',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='regra_fim_depois_do_inicio'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['profissional', 'inicio'], name='consulta_prof_inicio_idx'),
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grupo__isnull', True), ('paciente__isnull', False)), models.Q(('grupo__isnull', False), ('paciente__isnull', True)), _connector='OR'), name='consulta_paciente_ou_grupo'),
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='consulta_fim_depois_do_inicio'),
        ),
    ]
