# Generated by Django 5.2.18 on 2026-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('push', 'Notificação no aparelho')], max_length=10),
        ),
    ]
